TheBLVD/moth.social

app/lib/onboarding/onboarding_categories_production.yml
Generated with this short Ruby script feeding in the CSV table exported directly from Notion
```ruby
require 'csv'
require 'yaml'
csv = CSV.new(STDIN, headers: true)
categories = csv.group_by {|row| row['Main Category']}.map do |category, accounts|
{
'name' => category,
'accounts' => accounts.map {|row| row['Handle']}.to_a
}
end.to_a
puts categories.to_yaml
```
(Yep, I was a Rubyist long ago—a very helpful coincidence with the Mastodon codebase 😆)
=> Onboarding: update production suggested follows list

Gemfile, Gemfile.lock, config.ru, config/application.rb
Missed a couple of steps on the last go-round.
=> Enable dd profiler

app/lib/onboarding/onboarding_categories_production.yml
Shorten brief descriptions of suggested follows so they don't ellipse
https://linear.app/theblvd/issue/MAM-467/some-summary-field-lines-are-too-long-and-should-be-shortened
=> onboarding: Shorten suggested following descriptions (MAM-467)

app/lib/onboarding/onboarding_categories_production.yml
This adds the official Mammoth accounts to our suggested follows.
=> onboarding: add official Mammoth accounts to suggested (MAM-541)

.rubocop.yml, config/initializers/rack_attack.rb, spec/config/initializers/rack_attack_spec.rb
Turns out there are a couple other places API limits are defined.
=> up more api limits

app/lib/onboarding/v2/onboarding_categories_production.yml
Secret sauce 🍅:
```ruby
require 'csv'
require 'yaml'
csv = CSV.new(STDIN, headers: true)
categories = csv.group_by {|row| row['Main Category']}.map do |category, accounts|
{
'name' => category,
'items' => accounts.map do |row|
case row[0]
when 'Account'
{
'account' => row['Handle'],
'type' => 'account',
'summary' => row['Brief Description (3-5 words)']
}
when 'Hashtag'
{
'hashtag' => row['Handle'],
'type' => 'hashtag',
'bio' => row['Description'],
'summary' => row['Brief Description (3-5 words)']
}
end
end.to_a
}
end.to_a
puts categories.to_yaml
```
=> Onboarding: add hashtag suggestions

app/lib/onboarding/v2/onboarding_categories_production.yml
- Adds five suggested Developers follows
- Fixes typo on @rebeccawatson@mstdn.social
=> Onboarding: add developers to suggestions, fix typo

app/lib/onboarding/v2/onboarding_categories_production.yml
- Remove `@kathygriffin@mstdn.social` and `@taylorlorenz@mastodon.social` due to inactivity.
- Update `@brooklynmarie@mastodon.lol` to `@brooklynmarie@mastodon.social` due to closure of `mastodon.lol` instance.
- Add Humor category.
=> Onboarding: Refresh suggested follows

app/controllers/api/v2/follow_recommendations_graph_controller.rb
bump recommended account limit from 40->80
=> MAM-1717-babystep-1-more-or-better-suggested-follows

.env.production.sample, .env.test, app/controllers/api/v2/timelines/for_you_controller.rb, config/routes.rb
* Creates a new endpoint at `api/v2/timelines/for_you`
* Public timeline. No authentication required
* Returns Array of Statuses
* Same as you would from [timeline list](https://docs.joinmastodon.org/methods/timelines/#list)
* `GET /api/v1/timelines/list/:list_id HTTP/1.1`
List of curated and interesting accounts are managed by Mammoth@moth.social
https://staging.moth.social/api/v2/timelines/for_you
=> MAM-1754-create-a-for-you-endpoint-from-suggested-accounts-1

app/controllers/api/v2/timelines/for_you_controller.rb
check engagment metrics on reblog status, if it's a boost
=> MAM-1847-engagement-metrics-need-to-check-if-its-a-boosted-post-or-original

app/controllers/api/v2/follow_recommendations_graph_controller.rb
=> MAM-1988-exclude-outdated-follow-recommendations

app/controllers/api/v1/lists/accounts_controller.rb
Fix for calling Scheduler::PersonalizedForYouStatusesScheduler as async 👎
=> MAM-2255-add-to-list-fails

app/lib/personal_for_you.rb, app/workers/scheduler/status_stat_update_scheduler.rb, config/sidekiq.yml
adding beta direct follows to metrics collection
=> MAM-2482-add-metrics-gathering-engine-to-incoming-following-posts

app/lib/personal_for_you.rb
Caching user from AcctRely, means we need to bust it when making changes.
=> MAM-2565-for-you-feed-not-updating-with-pull-to-refresh-switches-not-retaining

app/lib/mammoth/curated_list.rb, app/workers/update_for_you_worker.rb
ForYou now adds Mammoth Curated List when settings toggle is enabled.
=> MAM-2694-show-the-mammoth-picks-switch-in-the-for-you-customization-view

.env.production.sample, config/sidekiq.yml, dist/mastodon-sidekiq-default.service, dist/mastodon-sidekiq-ingress.service, dist/mastodon-sidekiq-mailers.service, dist/mastodon-sidekiq-pull.service, dist/mastodon-sidekiq-push.service, dist/mastodon-sidekiq-scheduler.service
* Set MAMMOTH_FOR_YOU_SCHEDULER to .env value with default `5`
=> MAM-2712-make-foryou-status-update-worker-time-dynamtic

.github/workflows/Deploy-PROD.yml
- Missing build dependencies that production deployment.
=> Missing Build Debs

app/lib/for_you_feed_manager.rb, app/workers/update_for_you_worker.rb
* save for you statuses in batch, instead of individually.
=> MAM-3042-batch-save-foryou

app/controllers/api/v3/timelines/for_you_controller.rb
*disable auth check on for_you timeline
=> MAM-Patch-disable-jwt

app/controllers/api/base_controller.rb, app/controllers/api/v3/channels_controller.rb
=> MAM-Tim-patch

app/controllers/api/v3/timelines/for_you_controller.rb, app/lib/for_you_feed_manager.rb, app/lib/mammoth/channels.rb, app/lib/mammoth/status_origin.rb, app/lib/personal_for_you.rb, app/workers/update_for_you_worker.rb
* Friends Of Friends list populating correctly
* Breadcrumb label showing only those smarlists that the user is subscribed too & enabled in FY
* Breadcrumbs are also purged when the user's feed is rebuilt.
=> MAM-3089-friends-of-friends-dont-seem-to-be-running-correctly

app/controllers/api/v3/channels_controller.rb, app/controllers/api/v3/timelines/for_you_controller.rb, app/controllers/api/v3/timelines/statuses_controller.rb
[AppSignal Link](https://appsignal.com/the-blvd/sites/654a5c27d2a5e41095e78bec/exceptions/incidents/193/samples/654a5c27d2a5e41095e78bec-1409147111106364404216996417801)
=> MAM-3157-post-with-no-attribution-in-for-you

app/workers/update_for_you_worker.rb
* bump the mammoth picks threshold from 2 -> 4
=>  MAM-mammoth-pics-threshold

app/controllers/api/base_controller.rb
* capture and send JWT specific errors. 
errors available as namespaces transactions in AppSignal
=> MAM-3109-tim-chambers-seeing-empty-discover-tab

app/lib/onboarding/onboarding_categories_production.yml, app/lib/onboarding/v2/onboarding_categories_development.yml, app/lib/onboarding/v2/onboarding_categories_production.yml
* updating onboarding and suggestion list to Lisa Melton
=> MAM-3209-don-melton-is-in-our-onboarding 

app/workers/update_for_you_worker.rb
SKIP personalization when running load tests. Then see what the output is
Theory  duration of each job should come down as we've greatly reduced the active.record calls during the steps 1 & 2.
=> MAM-3095-load-test-20k-general-only

app/controllers/api/v3/timelines/for_you_controller.rb, app/lib/personal_for_you.rb
Resolve [SchduleError](https://appsignal.com/the-blvd/sites/654becaad2a5e41095e84d44/exceptions/incidents/537/samples/654becaad2a5e41095e84d44-575898136221802966817005176601)
=> MAM-000-Scheduling-error-in-fetch-names

app/lib/mammoth/users.rb, app/workers/scheduler/for_you_mammoth_scheduler.rb, app/workers/update_for_you_worker.rb
* Paginated fetch of mammoth users
* AccountRelay setup with optional throttle
=> MAM-3335-throttle-env-that-would-tell-the-scheduler-to-only-fetch-x-active

app/lib/mammoth/status_origin.rb
* pipeline breadcrumb set and expire
_based on_
```sh
redis-cli slowlog get 10
1) 1) (integer) 280
2) (integer) 1702348357
3) (integer) 10317
4) 1) "sadd"
2) "origin:for_you:AjajAlawneh@mas.to:111557567751232187"
3) "{\"source\":\"SmartList\",\"channel_id\":\"ea36ff02-7534-42d2-aeee-4f736c80da10\",\"title\":\"indieweb\",\"originating_account_id\":1110866937... (9 more bytes)"
5) "127.0.0.1:34152"
6) ""
2) 1) (integer) 279
2) (integer) 1702348281
3) (integer) 11366
4) 1) "sadd"
2) "origin:for_you:gsbr@moth.social:111562398848587138"
3) "{\"source\":\"SmartList\",\"channel_id\":\"f222deba-7fcb-49b9-be23-c32da1982d2b\",\"title\":\"news\",\"originating_account_id\":11019529599800... (5 more bytes)"
5) "127.0.0.1:34372"
6) ""
3) 1) (integer) 278
2) (integer) 1702345905
3) (integer) 10220
4) 1) …
```
=> MAM-redis-perf

app/lib/mammoth/channels.rb, app/lib/mammoth/status_origin.rb, app/workers/update_for_you_worker.rb
* Adjust breadcrumbs saving to Redis from sadd to zadd with pipeline instead of individual posts.
=> MAM-3520-reids-slow-log

dist/maint/README.md, dist/maint/cleanup_tasks.sh, dist/maint/mastodon-cleanup.service, dist/maint/mastodon-cleanup.timer, lib/tasks/db.rake
* Remove backups once they've been copied to S3
* Enable regular maintenance tasks. 
Adding regular cleanup tasks will reduce 'statuses' the largest table taking up 30%
=> MAM-3808-why-is-the-db-over-70gb-now

app/services/update_status_stat_service.rb
* Set client calls with user agent "getmammoth.app FY Agent"
=> MAM-3865-change-fysm-relay-user-agent
