- .rubocop.yml
- app/controllers/api/base_controller.rb
- spec/controllers/api/base_controller_spec.rb
After talking with @ShihabM it seems like the most useful solution is to raise the max limit to 500, pending his final decision.  This lets him set the limit himself via parameter, and also prevents people trying to pull like 10K statuses and crashing the server or whatever.
To be reviewed but not merged until @ShihabM gives the OK.
> MAM-170: Raise api max limit

- config/initializers/datadog-tracer.rb
Ideally, we have one service name in dd for each entrypoint - so moth.social, sidekiq, etc.  For historical reasons, certain trace instruments were given their own service name anyway, so we have to override them manually in order to see them grouped together appropriately on dd.
For the definition of "service": https://github.com/DataDog/dd-trace-rb/issues/2518#issuecomment-1376390455 and https://github.com/DataDog/dd-trace-rb/issues/2347#issuecomment-1301944164
for manually setting service_name: https://github.com/DataDog/dd-trace-rb/issues/2347#issuecomment-1325715145
> explictly set datadog service names

- app/controllers/api/v2/onboarding_follow_recommendations_controller.rb
As we've secured permission for all the suggested follows currently in the YAML, we should be able to present them, even though some accounts have 'discoverable' set to false on Mastodon.
> onboarding: Remove check for account discoverable in suggestions

- app/controllers/api/v1/accounts_controller.rb
- app/controllers/api/v1/tags_controller.rb
- spec/controllers/api/v1/accounts_controller_spec.rb
- spec/controllers/api/v1/tags_controller_spec.rb
- spec/controllers/api/v1/timelines/tag_controller_spec.rb
When we offer a number of follow options in onboarding, we want all of them to end up in the user's home feed.  So we'll add a parameter to rebuild the feed after every follow.
Right now, just as a POC, this is only implemented for tags.
> add rebuild param

- public/custom.css
This PR includes update to refine the existing custom css styles.
>  The existing styles were only available via the admin section as plain text pasted into an input. These styles are now in a separate file placed at: `/public/custom.css`. This enables adding custom css without having to go an copy and paste styles on the admin panel which is error prone, does not allow to keep version sor do any revision over changes. 
Updates to styles includes:
- Use custom accent color (blue) for primary call to action elements (buttons, inputs, etc)
- Update Settings section to use existing custom colors on dark mode
- Replace Mastodon logo for Mammoth icon on Settings section and mobile layout.
Timeline:
Settings:
Profile: 
Mobile:
> feat: improve custom css for dark and light mode

- public/custom.css
This PR includes styles fixes for the search input and results show on the side navigation.
Search column on the dark (default), high contrast and light mode.
> Fix: custom styles on search input and results

- app/controllers/api/v2/follow_recommendations_graph_controller.rb
guard accounts not on local instance
For the current iteration, we are going to reply to **NON** Moth.social users with a 404. This updates the check for username **AND** domain. 
So if you're not on moth.social we send a 404 before looking up your account with find_local
This will return error:
https://staging.moth.social/api/v2/follow_recommendations/?acct=jtomchak@mas.to
https://staging.moth.social/api/v2/follow_recommendations/?acct=jtomchak@moth.social
This will work:
https://staging.moth.social/api/v2/follow_recommendations/?acct=jtomchak@staging.moth.social
> MAM-1715-server-recommended-follow-v2-only-checking-username

- app/controllers/api/v1/lists/accounts_controller.rb
- app/controllers/api/v3/timelines/for_you_controller.rb
- app/lib/for_you_beta.rb
- config/routes.rb
> MAM-2310-add-parameter-to-to-v3-to-indicate-beta-group

- config/sidekiq.yml
This gives us some head room for rate limiting in the short term
> MAM-2343-bump-metrics-updating-from-5-minutes-to-60-minutes

- app/controllers/api/v3/channels_controller.rb
- app/lib/mammoth/channels.rb
* ensure correct errors when returning channel details
> MAM-2533-return-404-when-channel-by-id-is-not-found

- app/controllers/api/base_controller.rb
- app/controllers/api/v1/lists/accounts_controller.rb
- app/controllers/api/v3/timelines/for_you_controller.rb
- app/lib/personal_for_you.rb
- app/workers/scheduler/status_stat_update_scheduler.rb
*rely on logic for `mammoth_user?` rather than the Moth.Social 'Beta List' that needed to be manually curated through the UI.
> MAM-2544-remove-all-conditions-based-on-mothsocial-beta-list

- app/controllers/api/v3/channels_controller.rb
- app/controllers/api/v3/timelines/for_you_controller.rb
- app/lib/mammoth/channels.rb
- app/lib/personal_for_you.rb
- app/workers/scheduler/for_you_mammoth_scheduler.rb
- app/workers/scheduler/status_stat_update_scheduler.rb
- config/routes.rb
* Adds subscribe and unsubscribe endpoints that a Mammoth user can use to add/remove channels from their personal channel selection
* Acknowledged that 'get mammoth users' has two parts. All Mammoth users, and those that have been 'personalized'
>  MAM-2555-proxy-api-for-addingremoving-channel-subscriptions-through-mothsocial

- app/lib/mammoth/channels.rb
- app/workers/scheduler/channel_status_stat_update_scheduler.rb
- app/workers/scheduler/status_stat_update_scheduler.rb
- config/sidekiq.yml
* Adding Channels to metrics update engine. Added as a separate job from Mammoth Curated, follows, and following. Currently set aggressively at 2 minutes. Feels like we'll want this to be as accurate as possible and it's a finite about of accounts + statuses to check.
> MAM-2558-channel-statuses-added-to-metrics-engine

- app/lib/mammoth/channels.rb
- app/models/mammoth_channel_feed.rb
- app/workers/channel_feed_worker.rb
- app/workers/scheduler/channel_mammoth_statuses_scheduler.rb
- config/sidekiq.yml
* Create Channel Feeds based on channels and accounts of that channel
* What we end up with is a generated Channel Feed of status ids that meet the minimum engagement threshold. 
* Persisted by Channel ID
> MAM-2598-generate-status-feeds-from-channels

- app/controllers/api/base_controller.rb
- app/controllers/api/v3/timelines/channels_controller.rb
- app/models/feed.rb
- app/models/mammoth_channel_feed.rb
- app/workers/channel_feed_worker.rb
- app/workers/scheduler/channel_mammoth_statuses_scheduler.rb
- config/routes.rb
* Return Channel Statuses by channel id
* Return with pagination, like a list
* Current implementation is 0 minimum engagement filter
* Running every 2 minutes checking for new content
This will return statuses for Photography:
`https://staging.moth.social/api/v3/timelines/channels/80466334-64fa-42e1-8d61-fa3834abb190`
page two
`https://staging.moth.social/api/v3/timelines/channels/80466334-64fa-42e1-8d61-fa3834abb190?max_id=111053606868616245`
```json
[
{
"id": "111058670043051700",
"created_at": "2023-09-13T16:00:19.000Z",
"in_reply_to_id": null,
"in_reply_to_account_id": null,
"sensitive": false,
"spoiler_text": "",
"visibility": "public",
"language": "en",
"uri": "https://mastodon.art/users/jonwoodhamsartandphoto/statuses/111058670016733177",
"url": …
```
> MAM-2599-api-endpoints-for-each-channel-feed-by-channel-id

- app/controllers/api/base_controller.rb
- app/lib/mammoth/channels.rb
- app/lib/personal_for_you.rb
- app/workers/scheduler/channel_mammoth_statuses_scheduler.rb
- app/workers/update_for_you_worker.rb
- config/sidekiq.yml
* User's subscribed channels will be added to their ForYou feed
* Note. There is an edge case where you subscribe to a channel, you won't immediately see it in your ForYou feed until it's updated server side. That happens every 5 minutes.
> MAM-2600-users-foryou-feed-incorporates-their-subscribed-channels

- config/sidekiq.yml
Moving stat status collection job from 2m -> 10m.
> MAM-2709-stat-backoff-from-2m-10m

- .env.production.sample
- Gemfile
- Gemfile.lock
- app/controllers/api/base_controller.rb
- app/controllers/api/v3/channels_controller.rb
- app/controllers/api/v3/timelines/for_you_controller.rb
- app/lib/json_token.rb
* Enable server side, once the shared secret is in place, and mastodon web service is restarted. 
* Requires a shared secret embedded in the client and known to the server
* The secret itself is never transmitted from client to server. Only the generated JWT value
* Server will decode generated JWT for validation.
> MAM-2692-authenticated-calls-from-mammoth-to-mothsocial 

- app/controllers/api/v3/timelines/for_you_controller.rb
- app/lib/personal_for_you.rb
- app/workers/update_for_you_worker.rb
* ForYou Feed will filter channels from `enabled_channels` instead of subscribed channels
```bash
curl --location --request PUT 'https://staging.moth.social/api/v3/timelines/for_you/me?acct=jtomchak%40moth.social' \
--header 'Authorization: Bearer XXX' \
--form 'from_your_channels="0"' \
--form 'friends_of_friends="0"' \
--form 'curated_by_mammoth="1"' \
--form 'your_follows="0"' \
--form 'enabled_channels[]="8c4e6da2-ef00-443e-b8bd-427bdc5c145b"' \
--form 'enabled_channels[]="b8d94332-f4ee-4195-98ae-ec5be9233efe"'
```
> [!WARNING]  
> No selection requires 
```
--form 'enabled_channels[]="false"' \
```
> MAM-2789-when-adding-subscribed-channels-to-a-users-for-you-feed-well-need

- app/workers/for_you_feed_worker.rb
- app/workers/scheduler/for_you_statuses_scheduler.rb
- app/workers/update_for_you_worker.rb
- config/sidekiq.yml
- dist/mastodon-sidekiq-mammoth.service
This creates a queue specific to Mammoth work. Used solely in processing ForYou feed updates etc. 
Sidekiq queues `mammoth1` & `mammoth2` have both been created, enabled, and started on PROD in preperation
> MAM-2857-over-flow-on-pull-queue

- app/controllers/api/v3/timelines/for_you_controller.rb
- app/lib/personal_for_you.rb
- dist/mastodon-sidekiq-scheduler.service
When getting for_you_settings, if not already 'personal' then check the user's waitlist status.
> MAM-2878make-call-for-waitlist-status-be

- app/controllers/api/v3/channels_controller.rb
- app/controllers/api/v3/timelines/statuses_controller.rb
- app/lib/mammoth/channels.rb
- app/lib/mammoth/status_origin.rb
- app/models/status_origin.rb
- app/serializers/status_origin_serializer.rb
- app/workers/update_for_you_worker.rb
- config/routes.rb
- spec/fabricators/status_origin_fabricator.rb
- spec/models/status_origin_spec.rb
* save origin reason when adding status to a user's for you feed
* fetch status origin api GET `https://staging.moth.social/api/v3/timelines/for_you/statuses/11129536085876024`
* Trigger rebuild of FY when unsubscribing from smartlist
```json
[
{
"source": "SmartList",
"title": "Info Researchers",
"channel_id": "0549325f-9e32-45bf-89a8-8fecb239d71f",
"originating_account": {
"id": "109902962269738889",
"username": "mszll",
"acct": "mszll@datasci.social",
```
`source` currently includes 'SmartList' | 'MammothPick'
> MAM-2669-breadcrumbs-and-transparency-foryou-posts

- app/controllers/api/v2/follow_recommendations_graph_controller.rb
- app/controllers/api/v2/onboarding_follow_recommendations_controller.rb
- app/lib/onboarding/v2/onboarding_categories_development.yml
- app/lib/onboarding/v2/onboarding_categories_production.yml
- app/services/follow_recommendations_service.rb
- app/services/onboarding_account_recommendations_service.rb
- config/routes/api.rb
* Additional endpoint `/api/v2/onboarding_follow_recommendations/accounts` that will return only recommended accounts as an array. no hashtags or meta data
Try it out: https://staging.moth.social//api/v2/onboarding_follow_recommendations/accounts
Resolves MAM-2930
>  MAM-2930-make-a-new-endpoint-for-a-list-of-grouped-onboarding-accounts

- app/controllers/api/v2/follow_recommendations_graph_controller.rb
- app/services/follow_recommendations_service.rb
* updates for logic on follow suggestions
* local Moth.Social & Personalized accounts will get Friends of Friends
* under this scenario if the follows is 0 then they get Suggested Follows from V2
* otherwise return 404
>  MAM-3127-discordsuggested-follows

- .env.production.sample
- app/workers/scheduler/for_you_mammoth_scheduler.rb
Take the current 2.0 user's roughly 100 users and be able to run their update For you feed function X number of times using
> MAM-3095-load-test-20k-simulate

- app/workers/for_you_feed_worker.rb
- app/workers/scheduler/for_you_statuses_scheduler.rb
- app/workers/update_for_you_worker.rb
- config/sidekiq.yml
- dist/default/mastodon-sidekiq
- dist/default/mastodon-sidekiq-mammoth_critical
- dist/default/mastodon-sidekiq-mammoth_default
- dist/scaling-service/mastodon-sidekiq-<queuename>@.service
Creating flexible dedicated queues for Mammoth Specific work with larger database pools. 
These service files are created on the server, enabled, and started up. There is now mammoth 'default' and 'critical'. They are both listed as they help out the other when each is idle based on their own respective priority. Which is why you see the names reversed.
> MAM-3095-load-test-20k-queues

- app/lib/channel_feed_manager.rb
- app/lib/mammoth/channels.rb
- app/lib/mammoth/curated_list.rb
- app/lib/mammoth/status_origin.rb
- app/workers/scheduler/channel_mammoth_statuses_scheduler.rb
- app/workers/update_for_you_worker.rb
* reduce / eliminate UpdateForYou from making repeated active record calls. grouping them once by the already running channel update worker and using those.
> MAM-3095-load-test-20k-ar-reduce

- app/controllers/api/v3/timelines/for_you_controller.rb
- app/lib/personal_for_you.rb
Checking user status as a valid mammoth user, rather than specifically a 'personalized' mammoth user
> MAM-000-new-accounts-for-you

- app/controllers/api/v3/timelines/for_you_controller.rb
- app/lib/personal_for_you.rb
* Remove condițional check to return 'Mammoth Picks' when the user's ForYou returns zero.
* This can happen during pagination, it will eventually return 0 [Zero] and then start sending 'Mammoth Picks'
* Couple http error catches
> MAM-3238-on-refresh-of-foryou-feed-not-clearing-old-posts

- app/controllers/api/v4/timelines/for_you_controller.rb
- app/controllers/api/v4/timelines/statuses_controller.rb
- app/models/for_you_feed.rb
- config/routes/api.rb
* Versions for you timeline feed and logic to v4. Splitting out the current v3 that serves mammoth 1.0 users. 
* V4 doesn't have to validate you're a mammoth 1 or 2 user
* Still falls back to mammoth picks, but only if you have no generated for you feed
* Not effected by paginating to end of statuses, and then falling through to mammoth picks.
* Once deployed simplify V3 to only serve Mammoth Picks
See release steps: https://linear.app/theblvd/issue/MAM-3276/foryou-logging-mammoth-10-users-as-new-20-users-🤦‍♂️#comment-72d0d79b
>  MAM-3276-foryou-logging-mammoth-10-users-as-new-20-users

- .env.production.sample
- app/controllers/api/v3/timelines/for_you_controller.rb
- app/controllers/api/v4/timelines/for_you_controller.rb
- app/lib/personal_for_you.rb
- app/services/for_you_mammoth_service_check.rb
- app/workers/scheduler/for_you_mammoth_scheduler.rb
- config/routes/api.rb
* Enable ForYouWorker to be skipped in the event of being overloaded. This is manually enabled/disabled
* disables the scheduler from running mammoth user for you updates
* returns 'overloaded' as the user's for you setting `status` 
* `timelines/foryou/` returns cached MammothPicks with threshold enabled posts. Updated every 5 minutes.
* Re-enabled auth calls for client jwt. [MAM-3078](https://linear.app/theblvd/issue/MAM-3078/mammoth-auth-for-endpoints-needs-to-be-re-enabled)
> [!IMPORTANT]  
> MAMMOTH_OVERLOAD_ENABLE in the .env must be set to `true` and both web & sidekiq services restarted to have any effect.
>  MAM-3304-big-red-button

- app/controllers/api/base_controller.rb
- app/controllers/api/v4/timelines/for_you_controller.rb
- app/lib/personal_for_you.rb
* Feature.Moth.Social requires auth header for `api/personalize` http requests. Pass along that header from client to feature 
resolves [MAM-3369](https://linear.app/theblvd/issue/MAM-3387/add-featuremothsocial-auth-token-to-mothsocial-and-reable-personalize)
> MAM-3369-for-you-feed-for-rileyhbatmastodonsocial-not-updated-for-2-days

- Gemfile
- Gemfile.lock
- app/controllers/api/v3/admin/for_you_controller.rb
- config/appsignal.yml
- config/routes/api.rb
* adds HTTP PUT `/api/v3/admin/for_you` #update to moth.social with auth header. This will trigger a rebuild for user.
> MAM-3334-mothsocial-admin-for-a-rebuild-endpoint

- config/routes.rb
* Adds [apple-app-site-association](https://moth.social/apple-app-site-association) to .well-known route as well. 
Deployed to staging `https://staging.moth.social/.well-known/apple-app-site-association`
>  MAM-3411-host-apple-app-site-association-file-also-in-well-known-folder

- app/lib/mammoth/channels.rb
- app/lib/mammoth/curated_list.rb
- app/lib/personal_for_you.rb
* Query for statuses needs to be scoped to 'public' only.
> MAM-3450-private-messages-viewable-in-smart-list 

- app/lib/mammoth/status_origin.rb
- app/lib/personal_for_you.rb
* Update breadcrumb cleanup process for rebuilding ForYou feed.
* Continually trim user's breadcrumbs during batch updates.
```sh
debian@moth:~$ redis-cli slowlog get
1) 1) (integer) 517
2) (integer) 1706567160
3) (integer) 1269129
4) 1) "keys"
2) "origin:for_you:sznowicki@pol.social*"
5) "127.0.0.1:36766"
6) ""
```
I did the math,
109x faster 
99.2% faster
🚀 
```sh
debian@vps-814f87db:~$ redis-cli SLOWLOG GET
1) 1) (integer) 12631
2) (integer) 1706566778
3) (integer) 11397
4) 1) "scan"
2) "40963"
3) "MATCH"
4) "*origin:for_you:jtomchak@staging.moth.social*"
5) "COUNT"
6) "10000"
5) "127.0.0.1:40024"
6) ""
```
>  MAM-3832-unsubscribe-subscribe-blocking

- app/lib/mammoth/status_origin.rb
* missing arg on call to bulk_reasons
>  MAM-3832-unsubscribe-subscribe-blocking-missing-arg 

- config/appsignal.yml
Disables app specific metrics to AppSignal. Server metrics are still being sent by Statsd. (see image)
> Disable AppSignal
